In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris=load_iris()

In [5]:
lr=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)
lr

array([0.96078431, 0.92156863, 0.95833333])

In [6]:
np.average(lr)

0.9468954248366014

In [8]:
dt=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=3)
dt

array([0.98039216, 0.92156863, 1.        ])

In [9]:
np.average(dt)

0.9673202614379085

In [14]:
rf=cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)
rf

array([0.98039216, 0.94117647, 0.97916667])

In [15]:
np.average(rf)

0.9669117647058822

In [19]:
svm=cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)
svm

array([0.98039216, 0.96078431, 0.97916667])

In [20]:
np.average(svm)

0.9734477124183006